### ISSUE TITLE
Module not found when running with Python 3.11

### ISSUE THREAD

**Issue by fortysix2ahead** [fortysix2ahead/synophotos#1]
```
Traceback (most recent call last):
  File "~/synophotos/bin/synophotos", line 5, in <module>
    from synophotos.cli import main
  File "~/synophotos/lib/python3.11/site-packages/synophotos/__init__.py", line 15, in <module>
    from synophotos.webservice import SynoSession, WebService
  File "~/synophotos/lib/python3.11/site-packages/synophotos/webservice.py", line 12, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by fortysix2ahead** [comment]
closed by #2
